"""Domain errors for local CSV import."""

from __future__ import annotations

LOCAL_CSV_IMPORT_DISABLED = "LOCAL_CSV_IMPORT_DISABLED"
LOCAL_CSV_IMPORT_NOT_FOUND = "LOCAL_CSV_IMPORT_NOT_FOUND"
LOCAL_CSV_EXPORT_NOT_PREVIEWED = "LOCAL_CSV_EXPORT_NOT_PREVIEWED"
LOCAL_CSV_EXPORT_CONFLICT = "LOCAL_CSV_EXPORT_CONFLICT"
LOCAL_CSV_INVENTORY_MISMATCH = "LOCAL_CSV_INVENTORY_MISMATCH"
LOCAL_CSV_SECONDARY_CONFLICT = "LOCAL_CSV_SECONDARY_CONFLICT"
LOCAL_CSV_MATERIALIZATION_FAILED = "LOCAL_CSV_MATERIALIZATION_FAILED"
LOCAL_CSV_IMPORT_INVALID_STATUS = "LOCAL_CSV_IMPORT_INVALID_STATUS"
LOCAL_CSV_MATERIALIZATION_IN_PROGRESS = "LOCAL_CSV_MATERIALIZATION_IN_PROGRESS"
LOCAL_CSV_LEASE_LOST = "LOCAL_CSV_LEASE_LOST"
LOCAL_CSV_REQUIRES_REVIEW = "LOCAL_CSV_REQUIRES_REVIEW"
LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED = "LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED"
LOCAL_CSV_MATERIALIZATION_EXHAUSTED = "LOCAL_CSV_MATERIALIZATION_EXHAUSTED"
INVENTORY_NOT_WRITABLE = "INVENTORY_NOT_WRITABLE"
INVENTORY_CLOSED = "INVENTORY_CLOSED"
LATE_SYNC_REJECTED = "LATE_SYNC_REJECTED"
CONFLICT_POLICIES = frozenset({"SKIP", "REJECT"})


class LocalCsvImportError(Exception):
    def __init__(self, code: str, detail: str) -> None:
        super().__init__(detail)
        self.code = code


class LocalCsvImportDisabledError(LocalCsvImportError):
    def __init__(self) -> None:
        super().__init__(LOCAL_CSV_IMPORT_DISABLED, "Local CSV import is not enabled")
