"""Stable error-code allowlist for local CSV / package import workflows."""

from __future__ import annotations

from src.domain.local_csv_import.errors import (
    INVENTORY_CLOSED,
    INVENTORY_NOT_WRITABLE,
    LATE_SYNC_REJECTED,
    LOCAL_CSV_EXPORT_CONFLICT,
    LOCAL_CSV_EXPORT_NOT_PREVIEWED,
    LOCAL_CSV_IMPORT_DISABLED,
    LOCAL_CSV_IMPORT_INVALID_STATUS,
    LOCAL_CSV_IMPORT_NOT_FOUND,
    LOCAL_CSV_INVENTORY_MISMATCH,
    LOCAL_CSV_MATERIALIZATION_FAILED,
    LOCAL_CSV_SECONDARY_CONFLICT,
)

LOCAL_CSV_MATERIALIZATION_IN_PROGRESS = "LOCAL_CSV_MATERIALIZATION_IN_PROGRESS"
LOCAL_CSV_LEASE_LOST = "LOCAL_CSV_LEASE_LOST"
LOCAL_CSV_REQUIRES_REVIEW = "LOCAL_CSV_REQUIRES_REVIEW"
LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED = "LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED"
LOCAL_CSV_MATERIALIZATION_EXHAUSTED = "LOCAL_CSV_MATERIALIZATION_EXHAUSTED"
PACKAGE_CONFIRM_CONFLICT = "PACKAGE_CONFIRM_CONFLICT"
PACKAGE_INVALID_STATUS = "PACKAGE_INVALID_STATUS"
INVENTORY_NOT_FOUND = "INVENTORY_NOT_FOUND"
LOCAL_CSV_CONFLICT_POLICY_INVALID = "LOCAL_CSV_CONFLICT_POLICY_INVALID"

LOCAL_CSV_STABLE_ERROR_CODES: frozenset[str] = frozenset(
    {
        LOCAL_CSV_IMPORT_DISABLED,
        LOCAL_CSV_IMPORT_NOT_FOUND,
        LOCAL_CSV_EXPORT_NOT_PREVIEWED,
        LOCAL_CSV_EXPORT_CONFLICT,
        LOCAL_CSV_INVENTORY_MISMATCH,
        LOCAL_CSV_SECONDARY_CONFLICT,
        LOCAL_CSV_MATERIALIZATION_FAILED,
        LOCAL_CSV_IMPORT_INVALID_STATUS,
        LOCAL_CSV_MATERIALIZATION_IN_PROGRESS,
        LOCAL_CSV_LEASE_LOST,
        LOCAL_CSV_REQUIRES_REVIEW,
        LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED,
        LOCAL_CSV_MATERIALIZATION_EXHAUSTED,
        LOCAL_CSV_CONFLICT_POLICY_INVALID,
        INVENTORY_NOT_FOUND,
        INVENTORY_NOT_WRITABLE,
        INVENTORY_CLOSED,
        LATE_SYNC_REJECTED,
        PACKAGE_CONFIRM_CONFLICT,
        PACKAGE_INVALID_STATUS,
        "PACKAGE_NOT_FOUND",
        "PACKAGE_INVENTORY_MISMATCH",
        "LOCAL_INVENTORY_PACKAGE_EXPORT_CONFLICT",
    }
)

LOCAL_CSV_RETRYABLE_ERROR_CODES: frozenset[str] = frozenset(
    {
        LOCAL_CSV_MATERIALIZATION_FAILED,
        LOCAL_CSV_LEASE_LOST,
        LOCAL_CSV_MATERIALIZATION_IN_PROGRESS,
    }
)

LOCAL_CSV_PERMANENT_ERROR_CODES: frozenset[str] = frozenset(
    {
        LOCAL_CSV_CANONICAL_MATERIALIZATION_REJECTED,
        LOCAL_CSV_REQUIRES_REVIEW,
        LOCAL_CSV_MATERIALIZATION_EXHAUSTED,
        INVENTORY_CLOSED,
        INVENTORY_NOT_WRITABLE,
        LATE_SYNC_REJECTED,
        LOCAL_CSV_EXPORT_CONFLICT,
        LOCAL_CSV_SECONDARY_CONFLICT,
    }
)


class LocalCsvErrorCodeError(ValueError):
    def __init__(self, code: str) -> None:
        super().__init__(f"Unsupported local CSV error code: {code!r}")
        self.code = code


def normalize_stable_error_code(code: str | None, *, fallback: str) -> str:
    """Return an allowlisted code; never truncate silently to an unknown value."""
    candidate = (code or "").strip()
    if candidate in LOCAL_CSV_STABLE_ERROR_CODES:
        return candidate
    if fallback not in LOCAL_CSV_STABLE_ERROR_CODES:
        raise LocalCsvErrorCodeError(fallback)
    return fallback


def is_retryable_error_code(code: str | None) -> bool:
    return normalize_stable_error_code(
        code, fallback=LOCAL_CSV_MATERIALIZATION_FAILED
    ) in LOCAL_CSV_RETRYABLE_ERROR_CODES
