"""Minimal typing shim for pyodbc (binary wheel without py.typed)."""

from collections.abc import Iterable
from typing import Any

class IntegrityError(Exception): ...

def drivers() -> list[str]: ...
def connect(connstr: str, **kwargs: Any) -> Connection: ...

class Cursor:
    def execute(self, sql: str, *parameters: Any) -> Cursor: ...
    def executemany(self, sql: str, seq_of_parameters: Iterable[Any]) -> Cursor: ...
    def fetchone(self) -> Any: ...
    def fetchall(self) -> list[Any]: ...
    def close(self) -> None: ...
    @property
    def rowcount(self) -> int: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, *args: Any) -> None: ...

class Connection:
    def cursor(self) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
