/**
 * Core sandbox validation config: pure-core logic only (no React Native / Expo).
 * The device-dependent adapters (src/native, app) require the Expo dev toolchain and
 * are excluded here. Use `jest.config.js` (react-native preset) for on-device suites.
 */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  roots: ['<rootDir>/tests', '<rootDir>/src/core'],
  testMatch: [
    '<rootDir>/tests/base64ToBytes.test.ts',
    '<rootDir>/tests/compositeCursor.test.ts',
    '<rootDir>/tests/imageFilter.test.ts',
    '<rootDir>/tests/stability.test.ts',
    '<rootDir>/tests/photoDetection.test.ts',
    '<rootDir>/tests/incrementalScan.test.ts',
    '<rootDir>/tests/scanCoordinator.test.ts',
    '<rootDir>/tests/detectionStability.integration.test.ts',
    '<rootDir>/tests/logging.test.ts',
    '<rootDir>/tests/captureState.test.ts',
    '<rootDir>/tests/canExportSession.test.ts',
    '<rootDir>/tests/localAisleWork.test.ts',
    '<rootDir>/tests/captureSequence.test.ts',
    '<rootDir>/tests/backgroundUploadCore.test.ts',
    '<rootDir>/tests/mobileHardeningCore.test.ts',
    '<rootDir>/tests/featureFlags.test.ts',
    '<rootDir>/tests/uploadObservability.test.ts',
    '<rootDir>/tests/uploadPolicies.test.ts',
    '<rootDir>/tests/uploadLease.test.ts',
    '<rootDir>/tests/mobileHardeningCorrectionsCore.test.ts',
    '<rootDir>/tests/processingState.test.ts',
    '<rootDir>/tests/processingReadiness.test.ts',
    '<rootDir>/tests/labelPayloadContracts.test.ts',
    '<rootDir>/tests/productLabelChecksumVectors.test.ts',
    '<rootDir>/tests/productLabelMultiConsolidator.test.ts',
    '<rootDir>/tests/strictMultilabelCodeScan.test.ts',
    '<rootDir>/tests/mobileMultiLabelPhysical.test.ts',
    '<rootDir>/tests/positionLabelPayload.test.ts',
    '<rootDir>/tests/databaseCorruption.test.ts',
    '<rootDir>/tests/databaseMigrations.test.ts',
    '<rootDir>/tests/catalogRevision.test.ts',
    '<rootDir>/tests/localCsvAndReconcileConflictClassification.test.ts',
    '<rootDir>/tests/sessionPackageExportContract.test.ts',
    '<rootDir>/tests/processingService.test.ts',
    '<rootDir>/tests/offlineOperations.test.ts',
    '<rootDir>/tests/offlineSupplierLabelValidator.test.ts',
    '<rootDir>/tests/quantityCompleteness.test.ts',
    '<rootDir>/tests/supplierExportSemantics.test.ts',
    '<rootDir>/tests/localCsvExportPreflight.test.ts',
    '<rootDir>/tests/exportPrepCore.test.ts',
    '<rootDir>/tests/exportPrepFencing.memory.test.ts',
    '<rootDir>/tests/exportPrepBackfill.test.ts',
    '<rootDir>/tests/exportPrepSqlite.real.test.ts',
    '<rootDir>/tests/exportPrepDrain.test.ts',
    '<rootDir>/tests/exportPrepStagingCorrections.test.ts',
    '<rootDir>/tests/exportPrepBoundedZip.test.ts',
    '<rootDir>/tests/exportPrepBoundedZipCorrections.test.ts',
    '<rootDir>/tests/incrementalSha256.test.ts',
    '<rootDir>/tests/exportPrepUtf8.test.ts',
    '<rootDir>/tests/exportPrepIntegrity.test.ts',
    '<rootDir>/tests/exportPrepIntegrityCorrections.test.ts',
    '<rootDir>/tests/photoStableProducers.test.ts',
    '<rootDir>/tests/nativeContentHash.test.ts',
    '<rootDir>/tests/exportDraftLookup.test.ts',
    '<rootDir>/tests/exportDraftLookupInstrumentation.test.ts',
    '<rootDir>/tests/exportPreflightResolutionRedundancy.test.ts',
    '<rootDir>/tests/benchmarkHarnessCore.test.ts',
    '<rootDir>/tests/benchmarkFixtureOrder.test.ts',
    '<rootDir>/tests/benchmarkCorrectness.test.ts',
    '<rootDir>/tests/benchmarkDualCorrectness.test.ts',
    '<rootDir>/tests/benchmarkOfflineAisleSource.test.ts',
    '<rootDir>/tests/benchmarkPipelineOfflineAisle.test.ts',
    '<rootDir>/tests/jobsSnapshotFence.test.ts',
    '<rootDir>/tests/localCodeScanStrategy.test.ts',
    '<rootDir>/tests/exportPreflightLightStrongIntegrity.test.ts',
    '<rootDir>/tests/barcodeScannerConcurrency.test.ts',
  ],
  moduleNameMapper: {
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
  },
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: 'tsconfig.core.json' }],
  },
};
