"""Compatibility facade for API dependency providers."""

from __future__ import annotations

from src.api.deps.aisles import (  # noqa: F401
    get_activate_aisle_use_case,
    get_aisle_identification_configuration_query,
    get_aisle_job_launch_service,
    get_aisle_review_lifecycle_sync,
    get_cancel_aisle_job_use_case,
    get_create_aisle_use_case,
    get_deactivate_aisle_use_case,
    get_delete_aisle_source_asset_use_case,
    get_evaluate_authoritative_aisle_readiness,
    get_finalize_authoritative_aisle_use_case,
    get_get_aisle_merge_results_use_case,
    get_get_aisle_processing_status_use_case,
    get_list_aisle_assets_use_case,
    get_list_aisle_jobs_use_case,
    get_list_aisles_by_inventory_use_case,
    get_list_aisles_with_status_use_case,
    get_list_preliminary_reconciliations_use_case,
    get_persist_authoritative_local_code_scan_use_case,
    get_process_preliminary_reconciliations_use_case,
    get_reconcile_preliminary_detections_use_case,
    get_recover_aisle_processing_use_case,
    get_recover_stale_job_use_case,
    get_resolve_aisle_job_for_inventory_read_use_case,
    get_retry_aisle_job_use_case,
    get_run_aisle_merge_use_case,
    get_start_aisle_processing_use_case,
    get_update_aisle_code_use_case,
    get_upload_aisle_assets_use_case,
    get_upsert_preliminary_detection_use_case,
)
from src.api.deps.analytics import (  # noqa: F401
    get_analytics_cost_summary_service,
    get_analytics_query_service,
    get_compare_aisle_runs_use_case,
    get_compare_many_aisle_runs_use_case,
    get_export_aisle_benchmark_compare_csv_use_case,
    get_export_aisle_benchmark_run_csv_use_case,
    get_promote_aisle_operational_job_use_case,
)
from src.api.deps.capture import (  # noqa: F401
    get_assign_capture_session_group_to_existing_aisle_use_case,
    get_cancel_capture_session_use_case,
    get_capture_staging_time_metadata_extractor,
    get_close_capture_session_use_case,
    get_compute_capture_session_assignment_preview_use_case,
    get_compute_capture_session_groups_use_case,
    get_compute_materialized_capture_session_group_preview_use_case,
    get_create_aisle_and_assign_capture_session_group_use_case,
    get_create_capture_session_use_case,
    get_create_ordered_capture_session_use_case,
    get_get_capture_session_detail_use_case,
    get_get_capture_session_groups_use_case,
    get_get_ordered_capture_session_use_case,
    get_list_capture_sessions_use_case,
    get_materialize_capture_session_group_use_case,
    get_materialize_capture_session_use_case,
    get_seal_ordered_capture_session_use_case,
    get_update_capture_session_clock_offset_use_case,
    get_upload_capture_session_staging_items_use_case,
)
from src.api.deps.imports import (  # noqa: F401
    build_confirm_local_csv_import,
    get_confirm_dinamic_scanner_txt_import_use_case,
    get_confirm_local_csv_import_use_case,
    get_confirm_local_inventory_package_use_case,
    get_get_local_csv_import_use_case,
    get_get_local_inventory_package_use_case,
    get_preview_dinamic_scanner_txt_import_use_case,
    get_preview_local_csv_import_use_case,
    get_preview_local_inventory_package_use_case,
)
from src.api.deps.infrastructure import (  # noqa: F401
    get_aisle_location_label_artifact_repo,
    get_artifact_manifest_store,
    get_artifact_publication_outbox_store,
    get_artifact_storage,
    get_client_position_label_repo,
    get_client_supplier_label_profile_repo,
    get_finalization_assessment_service,
    get_image_position_label_detection_repo,
    get_inventory_status_reconciler,
    get_job_artifact_catalog_service,
    get_job_image_coverage_repo,
    get_job_retry_chain_service,
    get_job_source_asset_repo,
    get_job_stale_reconciler,
    get_manual_image_coverage_repo,
    get_manual_image_result_uow_factory,
    get_manual_position_override_repo,
    get_materialized_position_identity_reader,
    get_observability_inventory_guard,
    get_observability_metrics_service,
    get_operational_execution_config_resolver,
    get_position_materialization_service,
    get_position_reconciliation_repo,
    get_processing_event_repo,
    get_result_context_resolver,
    get_result_evidence_query_service,
    get_result_evidence_repo,
    get_run_auditability_service,
    get_supplier_extraction_profile_repo,
    get_worker_launch_service_dep,
)
from src.api.deps.inventory import (  # noqa: F401
    get_activate_supplier_extraction_profile_version_use_case,
    get_activate_supplier_prompt_config_version_use_case,
    get_client_recognition_config_use_case,
    get_clone_supplier_extraction_profile_use_case,
    get_create_client_supplier_use_case,
    get_create_client_use_case,
    get_create_inventory_use_case,
    get_create_supplier_extraction_profile_version_use_case,
    get_create_supplier_prompt_config_version_use_case,
    get_delete_supplier_reference_image_use_case,
    get_export_aisle_business_csv_use_case,
    get_export_aisle_results_csv_use_case,
    get_export_inventory_package_zip_use_case,
    get_export_inventory_results_use_case,
    get_export_inventory_summary_csv_use_case,
    get_get_active_supplier_extraction_profile_use_case,
    get_get_active_supplier_prompt_config_use_case,
    get_get_client_supplier_use_case,
    get_get_client_use_case,
    get_get_inventory_metrics_use_case,
    get_get_inventory_use_case,
    get_get_supplier_extraction_profile_by_version_use_case,
    get_get_supplier_prompt_config_use_case,
    get_get_supplier_reference_image_use_case,
    get_inventory_recognition_config_use_case,
    get_list_client_supplier_label_profiles_use_case,
    get_list_client_suppliers_use_case,
    get_list_clients_use_case,
    get_list_inventories_use_case,
    get_list_inventory_list_items_use_case,
    get_list_supplier_extraction_profiles_use_case,
    get_list_supplier_prompt_configs_use_case,
    get_list_supplier_reference_annotations_use_case,
    get_list_supplier_reference_images_use_case,
    get_raspberry_recognition_config_use_case,
    get_replace_supplier_reference_annotations_use_case,
    get_soft_delete_inventories_use_case,
    get_test_label_recognition_code_use_case,
    get_update_client_use_case,
    get_update_inventory_name_use_case,
    get_upload_supplier_reference_images_use_case,
    get_upsert_client_supplier_label_profile_use_case,
)
from src.api.deps.locations import (  # noqa: F401
    get_batch_render_aisle_location_labels_use_case,
    get_create_aisle_location_use_case,
    get_download_aisle_location_label_use_case,
    get_get_aisle_location_label_use_case,
    get_get_aisle_location_use_case,
    get_invalidate_aisle_location_label_use_case,
    get_issue_aisle_location_label_use_case,
    get_list_aisle_location_labels_use_case,
    get_list_aisle_locations_use_case,
    get_render_aisle_location_label_use_case,
    get_replace_aisle_location_label_use_case,
    get_update_aisle_location_use_case,
)
from src.api.deps.positions import (  # noqa: F401
    get_aisle_operational_positioning_view_use_case,
    get_aisle_positioning_sequence_use_case,
    get_code_scanner,
    get_confirm_merge_positions_use_case,
    get_confirm_position_use_case,
    get_create_manual_image_result_use_case,
    get_delete_position_use_case,
    get_effective_position_reader,
    get_export_aisle_code_scans_use_case,
    get_get_aisle_code_scan_review_signals_use_case,
    get_get_asset_processing_detail_use_case,
    get_get_position_code_scan_evidence_use_case,
    get_get_position_detail_use_case,
    get_invalidate_asset_result_use_case,
    get_list_aisle_code_scans_use_case,
    get_list_aisle_positions_use_case,
    get_list_asset_processing_use_case,
    get_list_job_image_results_use_case,
    get_list_position_override_history_use_case,
    get_list_processing_events_use_case,
    get_list_review_queue_use_case,
    get_manage_position_override_use_case,
    get_mark_position_image_mismatch_use_case,
    get_mark_position_unknown_use_case,
    get_match_aisle_code_scan_detections_use_case,
    get_position_override_scope_resolver,
    get_preview_merge_positions_use_case,
    get_processing_action_idempotency_service,
    get_reconcile_job_positions_use_case,
    get_reprocess_aisle_positioning_use_case,
    get_reprocess_asset_use_case,
    get_retry_asset_persistence_use_case,
    get_run_aisle_code_scan_use_case,
    get_send_asset_to_external_use_case,
    get_single_asset_command_executor,
    get_source_asset_content_reader,
    get_summarize_aisle_code_scans_use_case,
    get_update_position_code_use_case,
    get_update_product_quantity_use_case,
    get_update_product_sku_use_case,
)
from src.api.deps.security import (  # noqa: F401
    get_access_principal,
    get_capture_session_access_policy,
    get_inventory_access_policy,
    require_capture_session_upload_scope,
    require_client_scope,
    require_inventory_client_scope,
    require_raspberry_device_token,
)
from src.runtime.v3_deps import (
    get_aisle_repo,  # noqa: F401
    get_client_repo,  # noqa: F401
    get_client_supplier_repo,  # noqa: F401
    get_clock,  # noqa: F401
    get_code_scan_repo,  # noqa: F401
    get_evidence_repo,  # noqa: F401
    get_final_count_repo,  # noqa: F401
    get_inventory_repo,  # noqa: F401
    get_job_repo,  # noqa: F401
    get_mobile_preliminary_detection_repo,  # noqa: F401
    get_ordered_capture_processing_reservation,  # noqa: F401
    get_ordered_capture_session_repo,  # noqa: F401
    get_position_repo,  # noqa: F401
    get_preliminary_detection_reconciliation_repo,  # noqa: F401
    get_product_record_repo,  # noqa: F401
    get_recompute_consolidated_counts_use_case,  # noqa: F401
    get_review_action_repo,  # noqa: F401
    get_source_asset_repo,  # noqa: F401
    get_supplier_prompt_config_repo,  # noqa: F401
)
