import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0d1b2a', padding: 20, paddingTop: 52 },
  body: { flex: 1 },
  h1: { color: '#fff', fontSize: 22, fontWeight: '700', marginBottom: 12 },
  h2: { color: '#fff', fontSize: 18, fontWeight: '600', marginTop: 20, marginBottom: 8 },
  row: { color: '#e0e1dd', fontSize: 14, marginBottom: 4 },
  notif: { color: '#94d2bd', fontSize: 12, marginTop: 2 },
  error: { color: '#ff6b6b', marginBottom: 8, fontSize: 14 },
  muted: { color: '#94a3b8', marginVertical: 12 },
  input: {
    borderColor: '#3d5a80',
    borderWidth: 1,
    borderRadius: 10,
    color: '#fff',
    padding: 12,
    marginVertical: 8,
  },
  btn: {
    backgroundColor: '#1b9aaa',
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
    alignItems: 'center',
  },
  btnDisabled: { opacity: 0.4 },
  btnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  smallBtn: {
    backgroundColor: '#3d5a80',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    margin: 4,
  },
  smallBtnText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  nav: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between' },
  card: { borderColor: '#334155', borderWidth: 1, borderRadius: 12, padding: 12, marginVertical: 8 },
  cardTitle: { color: '#fff', fontWeight: '700', fontSize: 16, marginBottom: 4 },
  pendingBox: { marginTop: 8, marginBottom: 4 },
  gridRow: { justifyContent: 'space-between', gap: 8, marginBottom: 8 },
  photoCard: { width: '48%', borderColor: '#334155', borderWidth: 1, borderRadius: 10, padding: 8 },
  thumb: { width: '100%', height: 120, borderRadius: 8, backgroundColor: '#1e293b' },
  photoText: { color: '#cbd5e1', fontSize: 11, marginTop: 4 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: '#0d1b2a',
    borderColor: '#334155',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    maxHeight: '85%',
  },
  pickerList: { maxHeight: 160, marginVertical: 8 },
  pickerItem: {
    borderColor: '#334155',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
  },
  pickerItemActive: { borderColor: '#94d2bd', backgroundColor: '#1e293b' },
});
