"""Stable warning codes for analytics cost-summary responses."""

from __future__ import annotations

COST_SNAPSHOT_MISSING_FOR_SOME_JOBS = "COST_SNAPSHOT_MISSING_FOR_SOME_JOBS"
PARTIAL_COST_CAPTURE_PRESENT = "PARTIAL_COST_CAPTURE_PRESENT"
LEGACY_JOBS_WITHOUT_COST = "LEGACY_JOBS_WITHOUT_COST"
COST_PER_UNIT_NOT_AVAILABLE = "COST_PER_UNIT_NOT_AVAILABLE"
COUNTED_QUANTITY_NOT_AVAILABLE = "COUNTED_QUANTITY_NOT_AVAILABLE"
COUNTED_QUANTITY_SCOPE_CAPPED = "COUNTED_QUANTITY_SCOPE_CAPPED"
COUNTED_QUANTITY_PARTIAL_NOT_RETURNED = "COUNTED_QUANTITY_PARTIAL_NOT_RETURNED"
COUNTED_QUANTITY_IS_OPERATIONAL_CURRENT_STATE = "COUNTED_QUANTITY_IS_OPERATIONAL_CURRENT_STATE"
PROVIDER_MODEL_UNIT_COST_NOT_AVAILABLE = "PROVIDER_MODEL_UNIT_COST_NOT_AVAILABLE"
INVALID_COMPUTED_COST_PRESENT = "INVALID_COMPUTED_COST_PRESENT"
DATE_RANGE_CAPPED = "DATE_RANGE_CAPPED"

PARSER_WARNING_TO_ENDPOINT: dict[str, str] = {
    "invalid_computed_cost": INVALID_COMPUTED_COST_PRESENT,
}
