import sys
import tempfile
import types
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "backend"))
# The parser's package imports a backend-only pyodbc adapter transitively. The
# parser itself does not use it; a stub keeps this direct contract test local.
sys.modules.setdefault("pyodbc", types.ModuleType("pyodbc"))

from capture import CaptureError, CaptureService
from scanner_service import Reading


class FakeRecognition:
    def __init__(self, client_id="client-a", supplier_id="supplier-a") -> None:
        self.value = {
            "selection_mode": "SPECIFIC" if supplier_id else "ALL",
            "client_id": client_id,
            "supplier_id": supplier_id,
        }

    def selection(self):
        return self.value


def item_reading(sequence: int, raw: str = "D1|0123456789|SKU|1|X") -> Reading:
    return Reading(sequence, raw, 0, {
        "accepted": True, "classification": "ITEM",
        "recognition": {"results": {"ITEM": {"status": "VALID", "source": "DINAMIC"}}},
    })


def position_reading(sequence: int) -> Reading:
    return Reading(sequence, "json-not-exported", 0, {
        "accepted": True, "classification": "POSITION",
        "recognition": {"results": {"POSITION": {
            "status": "VALID", "source": "DINAMIC", "position_id": "POS1",
            "pallet": "04", "side": "RIGHT",
        }}},
    })


class CaptureServiceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.directory = Path(tempfile.mkdtemp())
        self.capture = CaptureService(FakeRecognition(), self.directory)

    def test_aisle_filename_order_duplicates_and_backend_parser_compatibility(self) -> None:
        # Parser compatibility uses a canonical D1 generated by the domain helper.
        from src.domain.product_labels.format import build_product_label_payload
        from src.application.services.dinamic_scanner_txt_parser import parse_dinamic_scanner_txt
        valid = build_product_label_payload(label_id="A1B2C3D4E5", internal_code="SKU", quantity=1)
        self.capture.start("PASILLO_04")
        self.capture.record(position_reading(1))
        self.capture.record(item_reading(2, valid))
        self.capture.record(item_reading(3, valid))
        result = self.capture.finish()
        body = (self.directory / "PASILLO_04.txt").read_bytes()
        self.assertEqual(result["filename"], "PASILLO_04.txt")
        self.assertEqual(
            body.decode("utf-8").splitlines(),
            ["POSITION|POS1|04|RIGHT", valid, valid],
        )
        parsed = parse_dinamic_scanner_txt(body)
        self.assertEqual(len(parsed.products), 2)
        self.assertTrue(all(product.position is not None for product in parsed.products))

    def test_invalid_aisle_and_missing_client_are_rejected(self) -> None:
        for value in ("../foo", "foo/bar", "/foo", "foo\\bar"):
            with self.subTest(value=value), self.assertRaisesRegex(CaptureError, "aisle_code_invalid"):
                self.capture.start(value)
        with self.assertRaisesRegex(CaptureError, "client_selection_required"):
            CaptureService(FakeRecognition(client_id=None), self.directory).start("A1")

    def test_specific_raw_and_nonexportable_positions_finish_without_txt(self) -> None:
        self.capture.start("A1")
        self.capture.record(Reading(1, "raw", 0, {"accepted": False, "classification": "REJECTED"}))
        self.capture.record(Reading(2, "raw", 0, {
            "accepted": True,
            "classification": "RAW",
            "recognition": {"selection_mode": "SPECIFIC"},
        }))
        self.capture.record(Reading(3, "v1", 0, {"accepted": True, "classification": "POSITION", "recognition": {"results": {"POSITION": {"status": "VALID", "source": "DINAMIC", "position_id": "P"}}}}))
        state = self.capture.snapshot()
        self.assertEqual(state["physical_count"], 3)
        self.assertEqual(state["f2_accepted_count"], 2)
        self.assertEqual(state["accepted_count"], 0)
        self.assertEqual(state["rejected_count"], 1)
        self.assertEqual(state["not_exportable_count"], 2)
        finished = self.capture.finish()
        self.assertEqual(finished["state"], "FINISHED")
        self.assertIsNone(finished["filename"])

    def test_existing_file_is_archived_and_new_export_keeps_canonical_name(self) -> None:
        target = self.directory / "A1.txt"
        target.write_text("existing", encoding="utf-8")
        self.capture.start("A1")
        self.capture.record(position_reading(1))
        result = self.capture.finish()
        self.assertEqual(result["state"], "FINISHED")
        self.assertEqual(result["filename"], "A1.txt")
        self.assertEqual(result["archived_filename"], ".archive/A1.1.txt")
        self.assertEqual(target.read_text(encoding="utf-8"), "POSITION|POS1|04|RIGHT\n")
        self.assertEqual(
            (self.directory / ".archive" / "A1.1.txt").read_text(encoding="utf-8"),
            "existing",
        )

        second = CaptureService(FakeRecognition(), self.directory)
        second.start("A1")
        second.record(item_reading(1, "D1|A|B|1|C"))
        second_result = second.finish()
        self.assertEqual(second_result["archived_filename"], ".archive/A1.2.txt")
        self.assertEqual(
            (self.directory / ".archive" / "A1.2.txt").read_text(encoding="utf-8"),
            "POSITION|POS1|04|RIGHT\n",
        )

    def test_write_error_keeps_capture_for_retry(self) -> None:
        fresh = CaptureService(FakeRecognition(), self.directory / "other")
        fresh.start("A2")
        fresh.record(position_reading(1))
        with patch("capture._write_atomic_preserving_existing", side_effect=OSError("disk full")):
            with self.assertRaisesRegex(CaptureError, "export_write_failed"):
                fresh.finish()
        self.assertFalse((self.directory / "other" / "A2.txt").exists())

    def test_export_failed_blocks_new_start_and_retry_preserves_records(self) -> None:
        self.capture.start("A1")
        self.capture.record(position_reading(1))
        self.capture.record(item_reading(2, "D1|A|B|1|C"))
        with patch("capture._write_atomic_preserving_existing", side_effect=OSError("temporary")):
            with self.assertRaisesRegex(CaptureError, "export_write_failed"):
                self.capture.finish()
        before = self.capture.snapshot()
        with self.assertRaisesRegex(CaptureError, "capture_requires_resolution"):
            self.capture.start("A2")
        with patch("capture._write_atomic_preserving_existing") as write:
            self.capture.finish()
        content = write.call_args.args[2]
        self.assertEqual(before["aisle_code"], "A1")
        self.assertEqual(content.splitlines(), ["POSITION|POS1|04|RIGHT", "D1|A|B|1|C"])

    def test_abort_start_removes_active_capture_without_records(self) -> None:
        self.capture.start("A1")
        rolled_back = self.capture.abort_start("scanner_not_started")
        self.assertEqual(rolled_back["state"], "IDLE")
        self.assertEqual(rolled_back["error"], "scanner_not_started")

    def test_empty_capture_finishes_without_txt(self) -> None:
        self.capture.start("EMPTY")
        result = self.capture.finish()
        self.assertEqual(result["state"], "FINISHED")
        self.assertIsNone(result["filename"])
        self.assertEqual(result["physical_count"], 0)

    def test_all_raw_is_exported_verbatim_in_order_with_duplicates(self) -> None:
        capture = CaptureService(FakeRecognition(supplier_id=None), self.directory / "all")
        capture.start("P1")
        for sequence, raw in enumerate(("ABC123", "XYZ456", "ABC123"), start=1):
            capture.record(Reading(sequence, raw, 0, {
                "accepted": True,
                "classification": "RAW",
                "recognition": {"selection_mode": "ALL"},
            }))
        state = capture.snapshot()
        self.assertEqual(state["physical_count"], 3)
        self.assertEqual(state["f2_accepted_count"], 3)
        self.assertEqual(state["accepted_count"], 3)
        self.assertEqual(state["rejected_count"], 0)
        self.assertEqual(state["not_exportable_count"], 0)
        finished = capture.finish()
        self.assertEqual(finished["state"], "FINISHED")
        self.assertEqual(finished["filename"], "P1.txt")
        self.assertEqual((self.directory / "all" / "P1.txt").read_bytes(), b"ABC123\nXYZ456\nABC123\n")


if __name__ == "__main__":
    unittest.main()
